// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Levi_Inventarization_Backend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220305082249_changedNamesOfEntities")]
    partial class changedNamesOfEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("Defects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-9833-45ca-9017-1ded701ef149"),
                            CreatedAt = new DateTime(2022, 1, 24, 17, 54, 39, 230, DateTimeKind.Local),
                            Description = "description1",
                            Image = "image1",
                            Name = "name1",
                            UpdateBy = new Guid("11111111-9833-45ca-9017-1ded701ef149")
                        },
                        new
                        {
                            Id = new Guid("22222222-9833-45ca-9017-1ded701ef149"),
                            CreatedAt = new DateTime(2022, 1, 24, 17, 54, 39, 230, DateTimeKind.Local),
                            Description = "description2",
                            Image = "image2",
                            Name = "name2",
                            UpdateBy = new Guid("22222222-9833-45ca-9017-1ded701ef149")
                        });
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4079c2e4-8579-4476-9a45-8dd424a23968"),
                            CreatedAt = new DateTime(2021, 1, 24, 17, 54, 39, 230, DateTimeKind.Local),
                            Name = "DepName",
                            UpdateBy = new Guid("068cf2ee-c07c-449d-b04a-7f78958f8605")
                        });
                });

            modelBuilder.Entity("Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8da1328-8403-439e-9d46-5dcc13b521f0"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "0",
                            Price = 0,
                            QRCode = "0",
                            Status = false,
                            UpdateBy = new Guid("6420e4ab-958b-4fe5-82b6-3bb3861696ed")
                        },
                        new
                        {
                            Id = new Guid("051b9d7b-a622-4d5d-bb0d-468317e16743"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1",
                            Price = 750,
                            QRCode = "1",
                            Status = false,
                            UpdateBy = new Guid("96572b53-a770-4ba3-a61f-76fae194c3c3")
                        },
                        new
                        {
                            Id = new Guid("7f6231da-8802-4977-842b-90e69394cb3f"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "2",
                            Price = 506,
                            QRCode = "2",
                            Status = false,
                            UpdateBy = new Guid("c9703891-fd0f-4d58-b81b-c0afdf6fedd7")
                        },
                        new
                        {
                            Id = new Guid("ffed5add-2e43-49ed-9171-138d100e036c"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "3",
                            Price = 759,
                            QRCode = "3",
                            Status = false,
                            UpdateBy = new Guid("0bf5dc0a-dfa3-46d2-91df-aa8992f5814f")
                        },
                        new
                        {
                            Id = new Guid("c6cfca97-797f-48e2-b0ce-f735e61f5ab3"),
                            Category = "Computers",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "4",
                            Price = 2600,
                            QRCode = "4",
                            Status = false,
                            UpdateBy = new Guid("6cf486b3-6320-484b-aaa0-dd7fb40258d7")
                        },
                        new
                        {
                            Id = new Guid("47f147e3-3da9-49a0-897a-6c772b985d84"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "5",
                            Price = 160,
                            QRCode = "5",
                            Status = false,
                            UpdateBy = new Guid("9a395175-f4f7-403a-963a-85b335bfecc8")
                        },
                        new
                        {
                            Id = new Guid("94039a14-6141-47ba-b64e-646891089dd8"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "6",
                            Price = 1518,
                            QRCode = "6",
                            Status = false,
                            UpdateBy = new Guid("0cef76f3-0f0a-443a-a827-2254f17f4295")
                        },
                        new
                        {
                            Id = new Guid("224cf715-93e8-4fd8-9298-764d9827bad8"),
                            Category = "Computers",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "7",
                            Price = 5250,
                            QRCode = "7",
                            Status = false,
                            UpdateBy = new Guid("75f37172-633f-4b21-a818-86b3d63f400d")
                        },
                        new
                        {
                            Id = new Guid("72d4e4b5-59b3-4f80-831e-709340cfdaa8"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "8",
                            Price = 5200,
                            QRCode = "8",
                            Status = false,
                            UpdateBy = new Guid("1e0c251c-6443-42da-811a-5873a9b1a589")
                        },
                        new
                        {
                            Id = new Guid("7e3d87e3-efa6-451b-8c2a-13230e8c2807"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "9",
                            Price = 2277,
                            QRCode = "9",
                            Status = false,
                            UpdateBy = new Guid("0226f727-f79f-456c-b313-8bf35f54c663")
                        },
                        new
                        {
                            Id = new Guid("5d5e2288-a094-47d1-aaaf-aed90a6c0d9c"),
                            Category = "Computers",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "10",
                            Price = 320,
                            QRCode = "10",
                            Status = false,
                            UpdateBy = new Guid("ecfb7e96-ae8a-4cd4-ad05-532cd6e9414b")
                        },
                        new
                        {
                            Id = new Guid("6e669e7e-3775-4dbb-9158-b69adff930c2"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "11",
                            Price = 2783,
                            QRCode = "11",
                            Status = false,
                            UpdateBy = new Guid("3d81712e-cc87-4044-9ff9-913d8c3f3bb5")
                        },
                        new
                        {
                            Id = new Guid("995b6d32-b0ef-4c35-bce0-db1109552b37"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "12",
                            Price = 7800,
                            QRCode = "12",
                            Status = false,
                            UpdateBy = new Guid("2f055992-528f-4298-ba6b-2d12aad6f68a")
                        },
                        new
                        {
                            Id = new Guid("0bd17248-41e1-4991-be41-ae060bfd2f34"),
                            Category = "Computers",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "13",
                            Price = 9750,
                            QRCode = "13",
                            Status = false,
                            UpdateBy = new Guid("34630812-71a5-44d7-a1b5-cd90174087b8")
                        },
                        new
                        {
                            Id = new Guid("3d41ef90-be84-492d-b58f-99c097a74ded"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "14",
                            Price = 3542,
                            QRCode = "14",
                            Status = false,
                            UpdateBy = new Guid("89171dd0-a549-4aab-8cae-8404caebb5e4")
                        },
                        new
                        {
                            Id = new Guid("d829adec-c005-4d29-bd6a-168f249b013e"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "15",
                            Price = 480,
                            QRCode = "15",
                            Status = false,
                            UpdateBy = new Guid("32b34ad6-1804-4ebf-a3bd-3d144b493a85")
                        },
                        new
                        {
                            Id = new Guid("3c8f2d60-fb38-48b6-910f-1e920e679fbb"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "16",
                            Price = 10400,
                            QRCode = "16",
                            Status = false,
                            UpdateBy = new Guid("7b9c8bd4-be69-4d72-8214-d84bf7bff6ac")
                        },
                        new
                        {
                            Id = new Guid("22a4e63d-bd34-4277-8de5-d7b703485ff4"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "17",
                            Price = 4301,
                            QRCode = "17",
                            Status = false,
                            UpdateBy = new Guid("b0e90551-560c-48a9-a9b5-d5f77d999a79")
                        },
                        new
                        {
                            Id = new Guid("55fce935-f9df-4657-a8fc-725488b31457"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "18",
                            Price = 4554,
                            QRCode = "18",
                            Status = false,
                            UpdateBy = new Guid("e73f26c3-d619-4a21-8a67-a327751783c1")
                        },
                        new
                        {
                            Id = new Guid("f2db931f-7918-48b0-a491-0dc1e26a09bc"),
                            Category = "Computers",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "19",
                            Price = 14250,
                            QRCode = "19",
                            Status = false,
                            UpdateBy = new Guid("632f26e7-a2a6-48fd-99c4-2bf3bff32725")
                        });
                });

            modelBuilder.Entity("Entities.InventorySetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Setups");
                });

            modelBuilder.Entity("Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec13f037-ec1a-4507-8db5-88c30c23b52e"),
                            CreatedAt = new DateTime(2021, 1, 24, 17, 54, 39, 230, DateTimeKind.Local),
                            DepartmentId = new Guid("4079c2e4-8579-4476-9a45-8dd424a23968"),
                            Name = "Name2"
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05510482-0605-443e-8271-806902ec15c0"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4409),
                            Email = "0",
                            IsAdmin = true,
                            LastName = "0",
                            Name = "0",
                            Password = "0",
                            Phone = "2",
                            UpdateBy = new Guid("15c04130-d682-4375-b34f-5f8e0f1116c4")
                        },
                        new
                        {
                            Id = new Guid("67e778fe-9fa2-4d2b-91f7-98b1ca0c4367"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4429),
                            Email = "1",
                            IsAdmin = false,
                            LastName = "1",
                            Name = "1",
                            Password = "1",
                            Phone = "3",
                            UpdateBy = new Guid("dbe025ae-a8cc-4db8-8d48-eedea5e38512")
                        },
                        new
                        {
                            Id = new Guid("bd5c95d2-85d1-438a-ac39-d9ce8c8b96aa"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4431),
                            Email = "2",
                            IsAdmin = true,
                            LastName = "2",
                            Name = "2",
                            Password = "2",
                            Phone = "0",
                            UpdateBy = new Guid("60a46e4b-286e-4273-92be-60b3641beb45")
                        },
                        new
                        {
                            Id = new Guid("dc086561-55f1-4be9-a075-4c67259a3821"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4434),
                            Email = "3",
                            IsAdmin = false,
                            LastName = "3",
                            Name = "3",
                            Password = "3",
                            Phone = "1",
                            UpdateBy = new Guid("0ce29313-c3f7-4f72-955b-53adc34bd060")
                        },
                        new
                        {
                            Id = new Guid("750b8b30-f473-4afc-ac0e-68257e446898"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4436),
                            Email = "4",
                            IsAdmin = true,
                            LastName = "4",
                            Name = "4",
                            Password = "4",
                            Phone = "6",
                            UpdateBy = new Guid("a1bd02a3-9c52-49d9-b0f5-4a5b44be428c")
                        },
                        new
                        {
                            Id = new Guid("fc2c4214-8696-4e28-a6d7-c83843e9d25c"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4442),
                            Email = "5",
                            IsAdmin = false,
                            LastName = "5",
                            Name = "5",
                            Password = "5",
                            Phone = "7",
                            UpdateBy = new Guid("5e19e15f-7fc4-4a2d-ba6e-67fc06c42212")
                        },
                        new
                        {
                            Id = new Guid("c5fdf333-9ecb-467f-8647-d24aea2d5c34"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4444),
                            Email = "6",
                            IsAdmin = true,
                            LastName = "6",
                            Name = "6",
                            Password = "6",
                            Phone = "4",
                            UpdateBy = new Guid("4598f6c4-6b86-4104-b3f4-ffdb99d123bf")
                        },
                        new
                        {
                            Id = new Guid("48a01d0d-9966-47b6-adee-3c134fe502fe"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4447),
                            Email = "7",
                            IsAdmin = false,
                            LastName = "7",
                            Name = "7",
                            Password = "7",
                            Phone = "5",
                            UpdateBy = new Guid("272b76ec-83b5-4b89-99cc-d23daacda6ea")
                        },
                        new
                        {
                            Id = new Guid("b6da3c1a-9cb3-42cc-a91f-6b3c47203c68"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4449),
                            Email = "8",
                            IsAdmin = true,
                            LastName = "8",
                            Name = "8",
                            Password = "8",
                            Phone = "10",
                            UpdateBy = new Guid("9fd7289a-d492-439b-8200-87e5b73828ef")
                        },
                        new
                        {
                            Id = new Guid("c1901d6a-be0e-43d4-827d-2369c0bc7e81"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4454),
                            Email = "9",
                            IsAdmin = false,
                            LastName = "9",
                            Name = "9",
                            Password = "9",
                            Phone = "11",
                            UpdateBy = new Guid("3bd8fa0d-f52c-41fa-ad20-55141a76adc5")
                        },
                        new
                        {
                            Id = new Guid("77273e46-7390-4bd5-8b47-c7d8df14ab7b"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4456),
                            Email = "10",
                            IsAdmin = true,
                            LastName = "10",
                            Name = "10",
                            Password = "10",
                            Phone = "8",
                            UpdateBy = new Guid("5b6c2679-8330-45e3-9196-248a96175326")
                        },
                        new
                        {
                            Id = new Guid("256aed38-39b1-4901-8a2a-4aa996257b4b"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4459),
                            Email = "11",
                            IsAdmin = false,
                            LastName = "11",
                            Name = "11",
                            Password = "11",
                            Phone = "9",
                            UpdateBy = new Guid("dbdef4ce-2396-4b97-ac64-3233ec5ea1b9")
                        },
                        new
                        {
                            Id = new Guid("7fa216b4-9ff3-4433-8877-ecf03807eeab"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4461),
                            Email = "12",
                            IsAdmin = true,
                            LastName = "12",
                            Name = "12",
                            Password = "12",
                            Phone = "14",
                            UpdateBy = new Guid("39040d4e-a224-44b0-9d5c-5f34b50d50b8")
                        },
                        new
                        {
                            Id = new Guid("5fb77a76-5eb0-4748-a48b-077a22e9b0da"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4465),
                            Email = "13",
                            IsAdmin = false,
                            LastName = "13",
                            Name = "13",
                            Password = "13",
                            Phone = "15",
                            UpdateBy = new Guid("bd056a3b-51dc-41d2-aea2-c6ae9c3c972f")
                        },
                        new
                        {
                            Id = new Guid("60ac99ab-4e78-4402-8d33-ccbb5502e071"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4468),
                            Email = "14",
                            IsAdmin = true,
                            LastName = "14",
                            Name = "14",
                            Password = "14",
                            Phone = "12",
                            UpdateBy = new Guid("e62d7fb2-d153-4b35-b5f8-235ee9ae929c")
                        },
                        new
                        {
                            Id = new Guid("decffedc-8213-439f-975b-4eea7f5d487b"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4470),
                            Email = "15",
                            IsAdmin = false,
                            LastName = "15",
                            Name = "15",
                            Password = "15",
                            Phone = "13",
                            UpdateBy = new Guid("c582797d-a8e9-478a-bbcb-92130c18c82c")
                        },
                        new
                        {
                            Id = new Guid("aaab4f97-a60b-4572-b2cb-5b80ddea7da7"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4473),
                            Email = "16",
                            IsAdmin = true,
                            LastName = "16",
                            Name = "16",
                            Password = "16",
                            Phone = "18",
                            UpdateBy = new Guid("33e31e4c-79b0-442c-a546-e35773e79c27")
                        },
                        new
                        {
                            Id = new Guid("52721195-193a-47e1-8e4e-8a7e87cb8d8b"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4478),
                            Email = "17",
                            IsAdmin = false,
                            LastName = "17",
                            Name = "17",
                            Password = "17",
                            Phone = "19",
                            UpdateBy = new Guid("d18b45db-06d3-419a-99d4-94cc27ada1be")
                        },
                        new
                        {
                            Id = new Guid("22ae9b75-717b-4d99-985f-564c6e0078f5"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4480),
                            Email = "18",
                            IsAdmin = true,
                            LastName = "18",
                            Name = "18",
                            Password = "18",
                            Phone = "16",
                            UpdateBy = new Guid("68dca140-9735-4bad-adb3-11d9b79601e1")
                        },
                        new
                        {
                            Id = new Guid("69ee4e5f-a0ad-429b-a34d-dfb6ce9c8d8b"),
                            CreatedAt = new DateTime(2022, 3, 5, 11, 22, 48, 879, DateTimeKind.Local).AddTicks(4483),
                            Email = "19",
                            IsAdmin = false,
                            LastName = "19",
                            Name = "19",
                            Password = "19",
                            Phone = "17",
                            UpdateBy = new Guid("2755d440-35b2-4c5d-85d2-88eeaa0b58a3")
                        });
                });

            modelBuilder.Entity("Entities.Defect", b =>
                {
                    b.HasOne("Entities.Inventory", "Inventory")
                        .WithMany("DefectsList")
                        .HasForeignKey("InventoryId");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Entities.Inventory", b =>
                {
                    b.HasOne("Entities.Department", null)
                        .WithMany("InventoryList")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.InventorySetup", b =>
                {
                    b.HasOne("Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Room", b =>
                {
                    b.HasOne("Entities.Department", null)
                        .WithMany("RoomsList")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Navigation("InventoryList");

                    b.Navigation("RoomsList");
                });

            modelBuilder.Entity("Entities.Inventory", b =>
                {
                    b.Navigation("DefectsList");
                });
#pragma warning restore 612, 618
        }
    }
}
