// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Levi_Inventarization_Backend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220305090204_addedDatesMockOfUserToInventory")]
    partial class addedDatesMockOfUserToInventory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("Defects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-9833-45ca-9017-1ded701ef149"),
                            CreatedAt = new DateTime(2022, 1, 24, 17, 54, 39, 230, DateTimeKind.Local),
                            Description = "description1",
                            Image = "image1",
                            Name = "name1",
                            UpdateBy = new Guid("11111111-9833-45ca-9017-1ded701ef149")
                        },
                        new
                        {
                            Id = new Guid("22222222-9833-45ca-9017-1ded701ef149"),
                            CreatedAt = new DateTime(2022, 1, 24, 17, 54, 39, 230, DateTimeKind.Local),
                            Description = "description2",
                            Image = "image2",
                            Name = "name2",
                            UpdateBy = new Guid("22222222-9833-45ca-9017-1ded701ef149")
                        });
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c475c532-fff5-4313-a40a-6f26c8e28702"),
                            CreatedAt = new DateTime(2021, 1, 24, 17, 54, 39, 230, DateTimeKind.Local),
                            Name = "DepName",
                            UpdateBy = new Guid("a1f56a4e-4e39-4d19-a1f7-68587a79f7f4")
                        });
                });

            modelBuilder.Entity("Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd952371-6969-4aa4-835f-db3ff36cf59e"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "80",
                            Price = 52000,
                            QRCode = "80",
                            Status = false,
                            UpdateBy = new Guid("258e4524-4218-4555-b51e-299f81a35ede"),
                            UserId = new Guid("d13caa1f-5ddb-4feb-a055-db5092c4707c")
                        },
                        new
                        {
                            Id = new Guid("e898ac6f-6ffd-4dc5-b149-c6c69d6fe0e5"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "85",
                            Price = 63750,
                            QRCode = "85",
                            Status = false,
                            UpdateBy = new Guid("77c946da-2c30-4e99-886c-403050f07bef"),
                            UserId = new Guid("3abe60bb-9f25-4438-9995-2336e61cad76")
                        },
                        new
                        {
                            Id = new Guid("c847f0bc-5d48-48c5-ab85-e8ab31360fe9"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "185",
                            Price = 5920,
                            QRCode = "185",
                            Status = false,
                            UpdateBy = new Guid("f0840a8b-c687-4075-980b-895271dd5b83"),
                            UserId = new Guid("0aa2f9b0-4107-4232-aff7-7415c4aea32c")
                        },
                        new
                        {
                            Id = new Guid("6ce48b12-28de-4c15-b733-db42896803ff"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "144",
                            Price = 93600,
                            QRCode = "144",
                            Status = false,
                            UpdateBy = new Guid("66787349-7280-4861-ac3a-e0a877e10cd8"),
                            UserId = new Guid("d3918cb8-5d99-418d-a807-4df4d51a6e50")
                        },
                        new
                        {
                            Id = new Guid("4365f0b3-f226-4a04-81d5-72b34ca4f8e4"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "168",
                            Price = 109200,
                            QRCode = "168",
                            Status = false,
                            UpdateBy = new Guid("d443933b-eaba-443f-ac16-2352ec9a2ab4"),
                            UserId = new Guid("9df0d11f-93db-420e-b13c-d1104a5ca757")
                        },
                        new
                        {
                            Id = new Guid("95d117b5-2504-42db-97d6-3461c826ed46"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "144",
                            Price = 93600,
                            QRCode = "144",
                            Status = false,
                            UpdateBy = new Guid("5a6718c6-973f-4700-8d03-3014f9614d7e"),
                            UserId = new Guid("91a887b9-41a7-4338-9fc8-a1d0c8a6568b")
                        },
                        new
                        {
                            Id = new Guid("fbb203ad-f9da-4ab3-b595-27eac34de69b"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "57",
                            Price = 14421,
                            QRCode = "57",
                            Status = false,
                            UpdateBy = new Guid("4e18e4c9-882e-4b5c-b1c5-e723c54b68b2"),
                            UserId = new Guid("38b0a5fd-0ba4-4a3e-b3cd-83d03db82e54")
                        },
                        new
                        {
                            Id = new Guid("7273679e-dc6b-4dc8-9603-3ffe1902f721"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "16",
                            Price = 10400,
                            QRCode = "16",
                            Status = false,
                            UpdateBy = new Guid("0533b8c2-6345-4882-83b3-d3d163b876b6"),
                            UserId = new Guid("c564ef09-ccca-415d-b0a3-6c9ecdd7f9b4")
                        },
                        new
                        {
                            Id = new Guid("435c140d-7846-4cb6-b970-a0ee22c5ebd7"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "104",
                            Price = 67600,
                            QRCode = "104",
                            Status = false,
                            UpdateBy = new Guid("37a2658f-0575-43c9-aa0c-c1709edf1c69"),
                            UserId = new Guid("fd71fd35-0aa4-4581-87cb-37d6c272afc3")
                        },
                        new
                        {
                            Id = new Guid("0b3dd925-a872-45f5-b4c2-c56c87948c51"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "137",
                            Price = 34661,
                            QRCode = "137",
                            Status = false,
                            UpdateBy = new Guid("eaa3a5f0-e0c5-4ac8-bbe6-29e7ff5452a1"),
                            UserId = new Guid("173a3e58-7cca-41c8-8fbd-78cb5b2e045c")
                        },
                        new
                        {
                            Id = new Guid("543815b5-e6b8-4e24-8ea8-5f269474f7b1"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "162",
                            Price = 40986,
                            QRCode = "162",
                            Status = false,
                            UpdateBy = new Guid("0db65ac0-2b6a-4853-8291-34b8921bff86"),
                            UserId = new Guid("ffb2ce3e-7420-41b4-89f3-dfcdf10f2580")
                        },
                        new
                        {
                            Id = new Guid("d816271c-6f85-4578-bebd-5c55d12aaf28"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "31",
                            Price = 23250,
                            QRCode = "31",
                            Status = false,
                            UpdateBy = new Guid("952ac06c-f1e2-4ba0-a758-8326f04a3c1f"),
                            UserId = new Guid("f5190a90-eacc-487b-8bba-7b08a3a2ebbe")
                        },
                        new
                        {
                            Id = new Guid("797ccac5-ef5a-4ccb-90ef-b29efad79394"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "58",
                            Price = 14674,
                            QRCode = "58",
                            Status = false,
                            UpdateBy = new Guid("92b98e4f-1831-4c49-aa5d-2bda04b9eaa5"),
                            UserId = new Guid("987fc04e-b0c8-464e-99e3-5e3a2e87bd7f")
                        },
                        new
                        {
                            Id = new Guid("51a08f39-1548-4d6c-8b08-8d59b7d3d5e1"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "152",
                            Price = 98800,
                            QRCode = "152",
                            Status = false,
                            UpdateBy = new Guid("8ca89006-bb71-4f4d-9f9d-5fcb61bc3f97"),
                            UserId = new Guid("d15f6a4c-b169-4c39-9558-8513f2876181")
                        },
                        new
                        {
                            Id = new Guid("e9e7437d-eaf4-45a4-8b84-dd5d34b74384"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "35",
                            Price = 1120,
                            QRCode = "35",
                            Status = false,
                            UpdateBy = new Guid("1bfb50b3-18bc-4b51-bab6-bcbf27056ca1"),
                            UserId = new Guid("9d9ac63f-c953-43a1-8725-84ab25bdacaf")
                        },
                        new
                        {
                            Id = new Guid("fc410b3e-8830-4760-bca6-7a2d1fe1c304"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 25, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "189",
                            Price = 47817,
                            QRCode = "189",
                            Status = false,
                            UpdateBy = new Guid("c1894c78-b13b-4de5-89a5-70fe0dca2b0e"),
                            UserId = new Guid("8e912945-7e2a-44b1-954d-82c309745a20")
                        },
                        new
                        {
                            Id = new Guid("0c79c6cb-407a-4568-ab06-fd7df3a2ff44"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "60",
                            Price = 39000,
                            QRCode = "60",
                            Status = false,
                            UpdateBy = new Guid("88a720d2-6f5a-4f18-9609-3f7e986ce22d"),
                            UserId = new Guid("a1d06e06-08e6-4ad6-a8d4-2a475ddeb939")
                        },
                        new
                        {
                            Id = new Guid("af1e11d5-cfc5-41ca-a7c6-ead87a425f02"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "11",
                            Price = 2783,
                            QRCode = "11",
                            Status = false,
                            UpdateBy = new Guid("c1ced48a-4639-4fa9-bdb8-09e716548d88"),
                            UserId = new Guid("19051554-4e0a-4746-ada7-c20df4ff759c")
                        },
                        new
                        {
                            Id = new Guid("d2ef8559-3566-4ac1-a310-38da25cad7e9"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "64",
                            Price = 41600,
                            QRCode = "64",
                            Status = false,
                            UpdateBy = new Guid("157aea15-2f6b-46cc-87e7-1c1935cb1393"),
                            UserId = new Guid("ec262457-7ec1-4f26-8ca1-14312ce8723f")
                        },
                        new
                        {
                            Id = new Guid("7fe88548-40da-4cb4-b839-7f51249912c7"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 2, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "51",
                            Price = 12903,
                            QRCode = "51",
                            Status = false,
                            UpdateBy = new Guid("db73193e-68f1-457e-8d5b-94c6a70bb7a8"),
                            UserId = new Guid("ad17121d-819a-47f6-9d61-53fab33ce93c")
                        });
                });

            modelBuilder.Entity("Entities.InventorySetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Setups");
                });

            modelBuilder.Entity("Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aafb04b3-e1cc-4627-9c4a-7501c329ef37"),
                            CreatedAt = new DateTime(2021, 1, 24, 17, 54, 39, 230, DateTimeKind.Local),
                            DepartmentId = new Guid("c475c532-fff5-4313-a40a-6f26c8e28702"),
                            Name = "Name2"
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d13caa1f-5ddb-4feb-a055-db5092c4707c"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(507),
                            Email = "0",
                            IsAdmin = true,
                            LastName = "0",
                            Name = "0",
                            Password = "0",
                            Phone = "2",
                            UpdateBy = new Guid("cda40989-58a1-4880-a4f6-7baabc90e439")
                        },
                        new
                        {
                            Id = new Guid("3abe60bb-9f25-4438-9995-2336e61cad76"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(529),
                            Email = "1",
                            IsAdmin = false,
                            LastName = "1",
                            Name = "1",
                            Password = "1",
                            Phone = "3",
                            UpdateBy = new Guid("10aee0bc-1c10-4fcf-a88d-14b2a13b4f0f")
                        },
                        new
                        {
                            Id = new Guid("0aa2f9b0-4107-4232-aff7-7415c4aea32c"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(532),
                            Email = "2",
                            IsAdmin = true,
                            LastName = "2",
                            Name = "2",
                            Password = "2",
                            Phone = "0",
                            UpdateBy = new Guid("f60183d8-01ca-45d2-abd5-edad316052ec")
                        },
                        new
                        {
                            Id = new Guid("d3918cb8-5d99-418d-a807-4df4d51a6e50"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(534),
                            Email = "3",
                            IsAdmin = false,
                            LastName = "3",
                            Name = "3",
                            Password = "3",
                            Phone = "1",
                            UpdateBy = new Guid("bb219361-c257-4f91-b694-eca6bc6e7a74")
                        },
                        new
                        {
                            Id = new Guid("9df0d11f-93db-420e-b13c-d1104a5ca757"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(536),
                            Email = "4",
                            IsAdmin = true,
                            LastName = "4",
                            Name = "4",
                            Password = "4",
                            Phone = "6",
                            UpdateBy = new Guid("738f37ea-f69e-4c90-8963-2d70fe6a2481")
                        },
                        new
                        {
                            Id = new Guid("91a887b9-41a7-4338-9fc8-a1d0c8a6568b"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(543),
                            Email = "5",
                            IsAdmin = false,
                            LastName = "5",
                            Name = "5",
                            Password = "5",
                            Phone = "7",
                            UpdateBy = new Guid("99bc8959-e438-4707-8962-6dcda2bf16ef")
                        },
                        new
                        {
                            Id = new Guid("38b0a5fd-0ba4-4a3e-b3cd-83d03db82e54"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(545),
                            Email = "6",
                            IsAdmin = true,
                            LastName = "6",
                            Name = "6",
                            Password = "6",
                            Phone = "4",
                            UpdateBy = new Guid("2cba6804-3956-4a72-94f1-9d8e92dcd939")
                        },
                        new
                        {
                            Id = new Guid("c564ef09-ccca-415d-b0a3-6c9ecdd7f9b4"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(548),
                            Email = "7",
                            IsAdmin = false,
                            LastName = "7",
                            Name = "7",
                            Password = "7",
                            Phone = "5",
                            UpdateBy = new Guid("d16c6675-8410-46ef-a311-99894e81c6ed")
                        },
                        new
                        {
                            Id = new Guid("fd71fd35-0aa4-4581-87cb-37d6c272afc3"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(550),
                            Email = "8",
                            IsAdmin = true,
                            LastName = "8",
                            Name = "8",
                            Password = "8",
                            Phone = "10",
                            UpdateBy = new Guid("904af6e8-9be6-402c-b182-3763d465abd0")
                        },
                        new
                        {
                            Id = new Guid("173a3e58-7cca-41c8-8fbd-78cb5b2e045c"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(555),
                            Email = "9",
                            IsAdmin = false,
                            LastName = "9",
                            Name = "9",
                            Password = "9",
                            Phone = "11",
                            UpdateBy = new Guid("b6dd9b2c-2bac-41a9-9ec5-78044b80d6cd")
                        },
                        new
                        {
                            Id = new Guid("ffb2ce3e-7420-41b4-89f3-dfcdf10f2580"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(558),
                            Email = "10",
                            IsAdmin = true,
                            LastName = "10",
                            Name = "10",
                            Password = "10",
                            Phone = "8",
                            UpdateBy = new Guid("21438f56-fcda-452f-b020-f93a4c61e0a6")
                        },
                        new
                        {
                            Id = new Guid("f5190a90-eacc-487b-8bba-7b08a3a2ebbe"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(561),
                            Email = "11",
                            IsAdmin = false,
                            LastName = "11",
                            Name = "11",
                            Password = "11",
                            Phone = "9",
                            UpdateBy = new Guid("8b286e9d-b399-4b70-be06-eec9d9e47c69")
                        },
                        new
                        {
                            Id = new Guid("987fc04e-b0c8-464e-99e3-5e3a2e87bd7f"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(563),
                            Email = "12",
                            IsAdmin = true,
                            LastName = "12",
                            Name = "12",
                            Password = "12",
                            Phone = "14",
                            UpdateBy = new Guid("5a45b48a-d135-418a-a26c-3326a9f04d6a")
                        },
                        new
                        {
                            Id = new Guid("d15f6a4c-b169-4c39-9558-8513f2876181"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(568),
                            Email = "13",
                            IsAdmin = false,
                            LastName = "13",
                            Name = "13",
                            Password = "13",
                            Phone = "15",
                            UpdateBy = new Guid("798b8769-9589-4b1a-ad8e-2b3762c18d2b")
                        },
                        new
                        {
                            Id = new Guid("9d9ac63f-c953-43a1-8725-84ab25bdacaf"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(596),
                            Email = "14",
                            IsAdmin = true,
                            LastName = "14",
                            Name = "14",
                            Password = "14",
                            Phone = "12",
                            UpdateBy = new Guid("b6038bf5-03a7-490b-8924-f51636589b2a")
                        },
                        new
                        {
                            Id = new Guid("8e912945-7e2a-44b1-954d-82c309745a20"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(599),
                            Email = "15",
                            IsAdmin = false,
                            LastName = "15",
                            Name = "15",
                            Password = "15",
                            Phone = "13",
                            UpdateBy = new Guid("a8a15a32-2b44-4553-9e4d-24e6bccb97f2")
                        },
                        new
                        {
                            Id = new Guid("a1d06e06-08e6-4ad6-a8d4-2a475ddeb939"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(602),
                            Email = "16",
                            IsAdmin = true,
                            LastName = "16",
                            Name = "16",
                            Password = "16",
                            Phone = "18",
                            UpdateBy = new Guid("ddd7d57f-3170-4255-8b77-0b231283173a")
                        },
                        new
                        {
                            Id = new Guid("19051554-4e0a-4746-ada7-c20df4ff759c"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(607),
                            Email = "17",
                            IsAdmin = false,
                            LastName = "17",
                            Name = "17",
                            Password = "17",
                            Phone = "19",
                            UpdateBy = new Guid("c539c850-669f-4a8e-9390-745e4a9d8e88")
                        },
                        new
                        {
                            Id = new Guid("ec262457-7ec1-4f26-8ca1-14312ce8723f"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(609),
                            Email = "18",
                            IsAdmin = true,
                            LastName = "18",
                            Name = "18",
                            Password = "18",
                            Phone = "16",
                            UpdateBy = new Guid("47388dd6-75da-4bad-beb8-410341be3327")
                        },
                        new
                        {
                            Id = new Guid("ad17121d-819a-47f6-9d61-53fab33ce93c"),
                            CreatedAt = new DateTime(2022, 3, 5, 12, 2, 4, 298, DateTimeKind.Local).AddTicks(612),
                            Email = "19",
                            IsAdmin = false,
                            LastName = "19",
                            Name = "19",
                            Password = "19",
                            Phone = "17",
                            UpdateBy = new Guid("6c34fff6-047f-4e16-9ac6-43548b9a916e")
                        });
                });

            modelBuilder.Entity("Entities.Defect", b =>
                {
                    b.HasOne("Entities.Inventory", "Inventory")
                        .WithMany("DefectsList")
                        .HasForeignKey("InventoryId");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Entities.Inventory", b =>
                {
                    b.HasOne("Entities.Department", null)
                        .WithMany("InventoryList")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.InventorySetup", b =>
                {
                    b.HasOne("Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Room", b =>
                {
                    b.HasOne("Entities.Department", null)
                        .WithMany("RoomsList")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Navigation("InventoryList");

                    b.Navigation("RoomsList");
                });

            modelBuilder.Entity("Entities.Inventory", b =>
                {
                    b.Navigation("DefectsList");
                });
#pragma warning restore 612, 618
        }
    }
}
