// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Levi_Inventarization_Backend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220325095928_testMock5")]
    partial class testMock5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("Defects");
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53f78352-d9a5-4356-a245-bef25d93e28e"),
                            CreatedAt = new DateTime(2021, 1, 24, 17, 54, 39, 230, DateTimeKind.Local),
                            Name = "Office Department",
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        });
                });

            modelBuilder.Entity("Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SetupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SetupId");

                    b.HasIndex("UserId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35bebde8-4d90-4c9c-9b08-285566a58cd1"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 2, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "aOUpeOKb",
                            Price = 44200,
                            QRCode = "QR 68",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("f1987f1b-c1ee-4fb0-81a1-9bad1ad9fc64"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "qlnzSfeM",
                            Price = 42251,
                            QRCode = "QR 167",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("8152bc21-e0a0-41cc-83f3-6b47eb5ebd31"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HzSPUOsb",
                            Price = 36179,
                            QRCode = "QR 143",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("b0b86b30-42b9-451c-bc67-4ade9f112fd9"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 27, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "eGOaqjYy",
                            Price = 80600,
                            QRCode = "QR 124",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("edf3bbbd-3a86-4a6d-9deb-02c78bfd7b44"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 4, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LxejnCIi",
                            Price = 14250,
                            QRCode = "QR 19",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("10ffdc22-56ad-4162-8c3a-919460ae9066"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LbHKptIg",
                            Price = 70200,
                            QRCode = "QR 108",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("89512c88-80e0-4e4d-a5e3-f6d4c7b75e34"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 26, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "wprUyabY",
                            Price = 41998,
                            QRCode = "QR 166",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        },
                        new
                        {
                            Id = new Guid("6747e895-60e0-433a-8cc1-b04e7afdcaf7"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 28, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XkEPQlWp",
                            Price = 72750,
                            QRCode = "QR 97",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        },
                        new
                        {
                            Id = new Guid("1534d191-0ba9-4481-8b09-3f29de9fda87"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "zPRzaXnK",
                            Price = 18722,
                            QRCode = "QR 74",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        },
                        new
                        {
                            Id = new Guid("c0848173-dce3-4b68-a426-e77829cfba56"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 28, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "yuPEQZCp",
                            Price = 81750,
                            QRCode = "QR 109",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9")
                        },
                        new
                        {
                            Id = new Guid("eb7a0af2-ab26-4ac3-a153-ca374c9f7808"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "hxcfSxdB",
                            Price = 18722,
                            QRCode = "QR 74",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9")
                        },
                        new
                        {
                            Id = new Guid("cc91d673-96f2-43ad-89cb-bbb5c8d3267d"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 24, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "vCEmDmDr",
                            Price = 49841,
                            QRCode = "QR 197",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9")
                        },
                        new
                        {
                            Id = new Guid("6c3dd301-8e7e-4e0b-afdd-fd76bb0f5277"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "soHGKRDh",
                            Price = 20999,
                            QRCode = "QR 83",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60")
                        },
                        new
                        {
                            Id = new Guid("c77dfd64-6c76-42ef-bba3-1564a03c842b"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 1, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "JwJxldZq",
                            Price = 22517,
                            QRCode = "QR 89",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60")
                        },
                        new
                        {
                            Id = new Guid("36a0c1de-eb22-4ca7-8b02-453a3f93e122"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 2, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "bLjREJxg",
                            Price = 17963,
                            QRCode = "QR 71",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60")
                        },
                        new
                        {
                            Id = new Guid("51196db2-016b-403e-ba80-63f4282a8e52"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 3, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "buRZJsmB",
                            Price = 10626,
                            QRCode = "QR 42",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d")
                        },
                        new
                        {
                            Id = new Guid("7d26e2c9-495b-4dbe-96de-3dd3d65fb714"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "bAgQcDvc",
                            Price = 14927,
                            QRCode = "QR 59",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d")
                        },
                        new
                        {
                            Id = new Guid("b37fa986-569b-4ce5-ad2c-67582f376e46"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 28, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TkArIRRl",
                            Price = 86250,
                            QRCode = "QR 115",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d")
                        },
                        new
                        {
                            Id = new Guid("1e52058d-26fb-42c9-a557-e610389b0ebf"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 4, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MKQAadRf",
                            Price = 750,
                            QRCode = "QR 1",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8")
                        },
                        new
                        {
                            Id = new Guid("90c9eecc-6580-406e-bc32-565c81e1118c"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 1, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "KGydBBgo",
                            Price = 68250,
                            QRCode = "QR 91",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8")
                        },
                        new
                        {
                            Id = new Guid("1539cec9-a6dd-4eac-9192-fe8e003de4ec"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "tKRSxwvt",
                            Price = 4000,
                            QRCode = "QR 125",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8")
                        },
                        new
                        {
                            Id = new Guid("921dd97b-6596-4bac-8258-56bc29bc003c"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ukysBzHr",
                            Price = 5280,
                            QRCode = "QR 165",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5")
                        },
                        new
                        {
                            Id = new Guid("6ebb5aea-1ddf-425b-9e71-fbc9a0db6173"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iAMLkskB",
                            Price = 27750,
                            QRCode = "QR 37",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5")
                        },
                        new
                        {
                            Id = new Guid("d8b5e7b9-b998-4191-a04d-c01958c85983"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 28, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "vjewQLln",
                            Price = 86250,
                            QRCode = "QR 115",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5")
                        },
                        new
                        {
                            Id = new Guid("907fd146-789a-4c9f-9a2f-c082aa9cd157"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 27, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "nQoFTOAO",
                            Price = 33143,
                            QRCode = "QR 131",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e")
                        },
                        new
                        {
                            Id = new Guid("68abd06d-de41-4bd7-aad5-8c7bf6b9bffe"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HydPONaM",
                            Price = 33902,
                            QRCode = "QR 134",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e")
                        },
                        new
                        {
                            Id = new Guid("e1385848-d2a9-4cbd-81b8-b90193c7f885"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "FdXuQzMU",
                            Price = 20999,
                            QRCode = "QR 83",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e")
                        },
                        new
                        {
                            Id = new Guid("c966ef6b-67d3-4dfa-ac55-1de88e1f6aba"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "lLSAxMgz",
                            Price = 34661,
                            QRCode = "QR 137",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        },
                        new
                        {
                            Id = new Guid("6a0ad719-70e4-4a97-976a-61bf7a68a38b"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "aBEuoelg",
                            Price = 45034,
                            QRCode = "QR 178",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        },
                        new
                        {
                            Id = new Guid("318c4db5-5d1c-454f-8bfd-89be2c1226ad"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 1, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "QSMotLxc",
                            Price = 54750,
                            QRCode = "QR 73",
                            RoomId = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        },
                        new
                        {
                            Id = new Guid("4ac0c977-97cd-4152-8a37-8f0542614026"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 4, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "EYPCdfDj",
                            Price = 14250,
                            QRCode = "QR 19",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("b144230f-0eb1-4825-b25f-575521d8f082"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 1, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "kmdsLncY",
                            Price = 68250,
                            QRCode = "QR 91",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("d1bcbeb5-b5d5-473b-9e7b-9138afed5046"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "epRJeFzx",
                            Price = 5280,
                            QRCode = "QR 165",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("3f88d153-2ce1-4ee1-b7f6-e59a3bf81bb4"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 28, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "fEVrpNVA",
                            Price = 24794,
                            QRCode = "QR 98",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("1eda9ec8-5bc6-446d-9d8f-e640ea4ac3f4"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 28, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "evIDAmPb",
                            Price = 72750,
                            QRCode = "QR 97",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("95b9df86-b3e3-456e-886b-7034b4241fb9"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 3, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OhEYFjkm",
                            Price = 18750,
                            QRCode = "QR 25",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("2280b9de-23c1-47e9-bcc7-676137be0e9d"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "QBnDVZqr",
                            Price = 31119,
                            QRCode = "QR 123",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        },
                        new
                        {
                            Id = new Guid("dcce5cc5-e0e3-456e-980f-b36445f4d41f"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 25, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HNOEzqxw",
                            Price = 43263,
                            QRCode = "QR 171",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        },
                        new
                        {
                            Id = new Guid("8b1ddcb9-f8fb-443f-8990-3ab757aea677"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 3, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LjsowIen",
                            Price = 11891,
                            QRCode = "QR 47",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        },
                        new
                        {
                            Id = new Guid("5f73a4b4-395a-4a64-accf-24967b00e46e"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "FQbfmvCY",
                            Price = 23400,
                            QRCode = "QR 36",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9")
                        },
                        new
                        {
                            Id = new Guid("93d850c7-35bd-4cd7-a6b6-f590ea7e094c"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 27, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ZrQzVzoY",
                            Price = 104250,
                            QRCode = "QR 139",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9")
                        },
                        new
                        {
                            Id = new Guid("c1b891f0-64df-434d-a518-6268f984a420"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 3, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RcBWRFZK",
                            Price = 11891,
                            QRCode = "QR 47",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9")
                        },
                        new
                        {
                            Id = new Guid("18c713df-e010-4bb8-92c9-de953914e3f5"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 4, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ALqkjjOq",
                            Price = 5566,
                            QRCode = "QR 22",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60")
                        },
                        new
                        {
                            Id = new Guid("858b8717-c5f9-46dc-9dd3-efe9c455fb9c"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CsWKAitm",
                            Price = 49400,
                            QRCode = "QR 76",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60")
                        },
                        new
                        {
                            Id = new Guid("8a786613-dd02-42d5-bcf6-ede9912a2f6e"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 3, 3, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "mKeAXcXJ",
                            Price = 6578,
                            QRCode = "QR 26",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60")
                        },
                        new
                        {
                            Id = new Guid("3216deaf-c2d3-459e-a0fc-40649197b278"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 27, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "xkNritHX",
                            Price = 90750,
                            QRCode = "QR 121",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d")
                        },
                        new
                        {
                            Id = new Guid("088033be-5470-45eb-81f5-a3778e1b9e2c"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 28, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SNBvaFGm",
                            Price = 29854,
                            QRCode = "QR 118",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d")
                        },
                        new
                        {
                            Id = new Guid("a99b688e-c393-4461-981f-7c3b99acb502"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 3, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "oRbehTpJ",
                            Price = 10626,
                            QRCode = "QR 42",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d")
                        },
                        new
                        {
                            Id = new Guid("08d29254-7738-4ab4-9b9c-457d8f611d02"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "mpojSITN",
                            Price = 0,
                            QRCode = "QR 0",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8")
                        },
                        new
                        {
                            Id = new Guid("b39ca608-8646-478c-ba44-4d73cacba022"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "iNdHvuzO",
                            Price = 9614,
                            QRCode = "QR 38",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8")
                        },
                        new
                        {
                            Id = new Guid("3aba7265-8b79-4f8d-8092-73ab0796bf16"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "fLZCBjzt",
                            Price = 119600,
                            QRCode = "QR 184",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8")
                        },
                        new
                        {
                            Id = new Guid("df4d6d48-d3e1-46a7-b882-83f076025658"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 24, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ZTfsNTuk",
                            Price = 50094,
                            QRCode = "QR 198",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5")
                        },
                        new
                        {
                            Id = new Guid("fbe2cb2e-d327-4dfb-a420-921d737e41c5"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 27, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DCeihJWo",
                            Price = 90750,
                            QRCode = "QR 121",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5")
                        },
                        new
                        {
                            Id = new Guid("01fb8a81-75f5-41c2-ae6a-dc15facd19f1"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "qBMlYwDM",
                            Price = 33902,
                            QRCode = "QR 134",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5")
                        },
                        new
                        {
                            Id = new Guid("efc50f2e-a801-482f-b2c0-78250ba076ba"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 26, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DmPHKtSJ",
                            Price = 96200,
                            QRCode = "QR 148",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e")
                        },
                        new
                        {
                            Id = new Guid("856f90c4-69ec-4e46-82b2-eab82e76c26b"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 2, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "WIdzRtxg",
                            Price = 14927,
                            QRCode = "QR 59",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e")
                        },
                        new
                        {
                            Id = new Guid("7799fff9-6340-4680-8653-de31cfaf0882"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 25, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "KGeLDbHU",
                            Price = 140250,
                            QRCode = "QR 187",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e")
                        },
                        new
                        {
                            Id = new Guid("d7758898-bd88-4c16-bfeb-11daec1b3a53"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 3, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "QlOZOzvL",
                            Price = 1440,
                            QRCode = "QR 45",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        },
                        new
                        {
                            Id = new Guid("acb8757d-f11c-4074-be88-d1f15ae88d60"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fqdlpxlt",
                            Price = 117000,
                            QRCode = "QR 180",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        },
                        new
                        {
                            Id = new Guid("376079d2-6487-4d3e-9fbf-9c2119ba5df2"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 4, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "tvHRnoGo",
                            Price = 14250,
                            QRCode = "QR 19",
                            RoomId = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        },
                        new
                        {
                            Id = new Guid("563885db-c1a9-42ec-8178-b58221d975a1"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "mLOgaUOg",
                            Price = 7800,
                            QRCode = "QR 12",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("0d903e44-15e4-4269-ae50-31c50c64f7aa"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 26, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "hVBBOPZb",
                            Price = 101400,
                            QRCode = "QR 156",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("813316fb-d453-48b9-a053-26e895ced3d1"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 2, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "hjMMNSwv",
                            Price = 1600,
                            QRCode = "QR 50",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("8c22fb46-3b4c-420e-a7b9-d3d432b5739d"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "bGjkoZpB",
                            Price = 104000,
                            QRCode = "QR 160",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("27b61faf-73ed-4c37-8422-2381f3fba99f"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 4, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "cRCnMfVD",
                            Price = 759,
                            QRCode = "QR 3",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("7cdb72e5-4228-4718-a0bb-932dbfe1ec2f"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 4, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "dlwYuObP",
                            Price = 506,
                            QRCode = "QR 2",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("203b655f-2505-4b58-ab3a-87d9d4f6635a"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ecPXYgaw",
                            Price = 63750,
                            QRCode = "QR 85",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        },
                        new
                        {
                            Id = new Guid("5c76dea8-75ad-4301-b877-aa640a07c900"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BBSlBmzT",
                            Price = 3520,
                            QRCode = "QR 110",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        },
                        new
                        {
                            Id = new Guid("e25ef516-c6e5-4413-9b20-8efe5d41fee5"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 28, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XreWfkbC",
                            Price = 75400,
                            QRCode = "QR 116",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        },
                        new
                        {
                            Id = new Guid("fbd6f412-c6b0-42ab-ba43-562e128acef2"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "evaICgju",
                            Price = 117000,
                            QRCode = "QR 180",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9")
                        },
                        new
                        {
                            Id = new Guid("40061b40-d668-4c45-a6f7-9219ce002cad"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 4, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DfhLTZyS",
                            Price = 5566,
                            QRCode = "QR 22",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9")
                        },
                        new
                        {
                            Id = new Guid("630736af-1df8-429f-bf6f-f2de29dfbf75"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 3, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "cALjkAeJ",
                            Price = 11891,
                            QRCode = "QR 47",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9")
                        },
                        new
                        {
                            Id = new Guid("dfc5a46d-3953-4cf3-a8c5-d266f1bc4071"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IGvahnbL",
                            Price = 5280,
                            QRCode = "QR 165",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60")
                        },
                        new
                        {
                            Id = new Guid("a8f9dd85-4fb2-4f21-b590-30c9387a3d41"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 3, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "nyRLDQfG",
                            Price = 32250,
                            QRCode = "QR 43",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60")
                        },
                        new
                        {
                            Id = new Guid("94d4bf7f-558e-4b4a-9798-ffe6be52b92d"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "pPhlHVkq",
                            Price = 36179,
                            QRCode = "QR 143",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60")
                        },
                        new
                        {
                            Id = new Guid("a8a233a6-a11b-40b6-937b-328770abe076"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 25, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "sMiGkrZK",
                            Price = 47817,
                            QRCode = "QR 189",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d")
                        },
                        new
                        {
                            Id = new Guid("1b033a21-f0fe-4d89-8b91-85ffb26dcb25"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LGCsXGXm",
                            Price = 34661,
                            QRCode = "QR 137",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d")
                        },
                        new
                        {
                            Id = new Guid("3c83e66d-b7aa-4e13-8957-d75542beb883"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 3, 4, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TQrvfjDq",
                            Price = 4554,
                            QRCode = "QR 18",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d")
                        },
                        new
                        {
                            Id = new Guid("a07053d4-0ad2-42ca-b0d9-d2ee8334ab5c"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LDKKolCw",
                            Price = 109200,
                            QRCode = "QR 168",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8")
                        },
                        new
                        {
                            Id = new Guid("3a00445c-1236-405e-b5ed-d3b3039d0d07"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "hYdRmElz",
                            Price = 40227,
                            QRCode = "QR 159",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8")
                        },
                        new
                        {
                            Id = new Guid("de5b1add-ef5a-4a94-b7cd-b733aac14500"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DHsJjPYm",
                            Price = 78000,
                            QRCode = "QR 120",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8")
                        },
                        new
                        {
                            Id = new Guid("7698bcf4-a80b-4eeb-a281-ff98bbce91f8"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 2, 28, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "dZSlvdrg",
                            Price = 81750,
                            QRCode = "QR 109",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5")
                        },
                        new
                        {
                            Id = new Guid("765f21de-c4cc-4785-8347-f21431e693da"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "gNdDeALr",
                            Price = 5280,
                            QRCode = "QR 165",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5")
                        },
                        new
                        {
                            Id = new Guid("9a0cf7bd-3f9c-46e7-86dd-7130f2d629b6"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 26, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "bfUtCYxg",
                            Price = 5280,
                            QRCode = "QR 165",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5")
                        },
                        new
                        {
                            Id = new Guid("aa21c052-b79d-4869-909e-f734220b812f"),
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2022, 2, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RxSswpkz",
                            Price = 33902,
                            QRCode = "QR 134",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UserId = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e")
                        },
                        new
                        {
                            Id = new Guid("42db678d-310b-4f29-9a28-8ed3c258929a"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 3, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "zdOWgHAG",
                            Price = 18200,
                            QRCode = "QR 28",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UserId = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e")
                        },
                        new
                        {
                            Id = new Guid("be706e99-4124-48cd-b521-1d761ab9f8e5"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "fYsfdtrb",
                            Price = 113250,
                            QRCode = "QR 151",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UserId = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e")
                        },
                        new
                        {
                            Id = new Guid("36ed4b4a-88fb-41b9-851b-9c057203d317"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 27, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "kNxkHOoC",
                            Price = 90750,
                            QRCode = "QR 121",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        },
                        new
                        {
                            Id = new Guid("18dd8900-8c12-4d80-b80e-40a803336bed"),
                            Category = "Furniture",
                            CreatedAt = new DateTime(2022, 2, 26, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "VrNEjCuW",
                            Price = 36938,
                            QRCode = "QR 146",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        },
                        new
                        {
                            Id = new Guid("0d13028b-37ee-4482-ad3a-a1c80876c12c"),
                            Category = "Computers",
                            CreatedAt = new DateTime(2022, 3, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TzOgFxLO",
                            Price = 9750,
                            QRCode = "QR 13",
                            RoomId = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            SetupId = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Status = false,
                            UpdateBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb")
                        });
                });

            modelBuilder.Entity("Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bef8e9b-4f39-4b43-9a8f-c7b900b96afd"),
                            CreatedAt = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("53f78352-d9a5-4356-a245-bef25d93e28e"),
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("1f8a08c4-f535-4807-83cc-6c74a76d3676"),
                            CreatedAt = new DateTime(2022, 3, 4, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("53f78352-d9a5-4356-a245-bef25d93e28e"),
                            Name = "Node"
                        },
                        new
                        {
                            Id = new Guid("e49c6469-cdd8-43af-b636-ee816b294c14"),
                            CreatedAt = new DateTime(2022, 3, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("53f78352-d9a5-4356-a245-bef25d93e28e"),
                            Name = ".Net"
                        });
                });

            modelBuilder.Entity("Entities.Setup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Setups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("428b81df-44a1-4502-aafd-8a4e4a406594"),
                            Category = "WorkPlaces",
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6201),
                            Name = "Ruby Work Desk",
                            QRCode = "QRCode",
                            RoomName = "Ruby",
                            Status = false,
                            UpdatedAt = new DateTime(2022, 3, 9, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65")
                        },
                        new
                        {
                            Id = new Guid("ed0e1f5c-283a-4f1a-858c-0539e24a8ebe"),
                            Category = "WorkPlaces",
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6221),
                            Name = "Node Work Desk",
                            QRCode = "QRCode",
                            RoomName = "Node",
                            Status = false,
                            UpdatedAt = new DateTime(2022, 3, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599")
                        },
                        new
                        {
                            Id = new Guid("b7c7e2e3-1f03-4ce6-a845-84adf47af4fa"),
                            Category = "WorkPlaces",
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6225),
                            Name = ".Net Work Desk",
                            QRCode = "QRCode",
                            RoomName = ".Net",
                            Status = false,
                            UpdatedAt = new DateTime(2022, 3, 7, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            UserId = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a")
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SetupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SetupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdateBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SetupId")
                        .IsUnique()
                        .HasFilter("[SetupId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a7a3da3-d6a7-4931-b8b4-7cdfa1e38d65"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(5971),
                            Email = "0",
                            IsAdmin = true,
                            LastName = "",
                            Name = "",
                            Password = "0",
                            Phone = "2",
                            UpdateBy = new Guid("2df68843-b482-46d5-8966-2338cefea001")
                        },
                        new
                        {
                            Id = new Guid("277bafb7-2e12-4b69-8cc8-86fd51b02599"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6019),
                            Email = "1",
                            IsAdmin = false,
                            LastName = "P",
                            Name = "E",
                            Password = "1",
                            Phone = "3",
                            UpdateBy = new Guid("0b96352e-41d9-4b11-96d4-79cac9df62c6")
                        },
                        new
                        {
                            Id = new Guid("1814522f-0ad6-4ec8-8e0a-027650ec506a"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6037),
                            Email = "2",
                            IsAdmin = false,
                            LastName = "Pl",
                            Name = "kw",
                            Password = "2",
                            Phone = "0",
                            UpdateBy = new Guid("e124d9af-0229-4ec8-bfe5-0eaf3da6ccd2")
                        },
                        new
                        {
                            Id = new Guid("d96059d7-a233-47f4-a83e-7c59910d25d9"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6043),
                            Email = "3",
                            IsAdmin = true,
                            LastName = "lyS",
                            Name = "JBJ",
                            Password = "3",
                            Phone = "1",
                            UpdateBy = new Guid("fcca91ed-85c6-4d83-b0d6-0bce294c61a3")
                        },
                        new
                        {
                            Id = new Guid("76e0b472-0466-4496-b7a4-3d64367f2a60"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6050),
                            Email = "4",
                            IsAdmin = false,
                            LastName = "SKVy",
                            Name = "CzpO",
                            Password = "4",
                            Phone = "6",
                            UpdateBy = new Guid("40c8a261-4cbb-417b-8f24-857b6fbec60a")
                        },
                        new
                        {
                            Id = new Guid("6c227153-efd1-4e94-9d44-efc8f756be2d"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6062),
                            Email = "5",
                            IsAdmin = false,
                            LastName = "lenfx",
                            Name = "KiEhP",
                            Password = "5",
                            Phone = "7",
                            UpdateBy = new Guid("14d73128-04a4-45d9-ad44-9e7dfc2e7c44")
                        },
                        new
                        {
                            Id = new Guid("e38923a3-697e-4405-ab97-5fa3020df6c8"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6068),
                            Email = "6",
                            IsAdmin = true,
                            LastName = "tHIfxH",
                            Name = "RPLgAB",
                            Password = "6",
                            Phone = "4",
                            UpdateBy = new Guid("4b05fb90-b4bf-46aa-8f48-ece6eb596fa3")
                        },
                        new
                        {
                            Id = new Guid("f8a827d7-7c72-4fac-a919-03478aa408b5"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6114),
                            Email = "7",
                            IsAdmin = false,
                            LastName = "NvtGGOQ",
                            Name = "vxUpzqI",
                            Password = "7",
                            Phone = "5",
                            UpdateBy = new Guid("5175be64-f693-4ac8-a760-e0d11dcf7c58")
                        },
                        new
                        {
                            Id = new Guid("e7c2e230-6377-4e2c-b6f5-ecd2ca836b8e"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6122),
                            Email = "8",
                            IsAdmin = false,
                            LastName = "hPvhWmRT",
                            Name = "pWacUGJq",
                            Password = "8",
                            Phone = "10",
                            UpdateBy = new Guid("d69e69cc-d07e-41b7-85d8-04c5339c4f0f")
                        },
                        new
                        {
                            Id = new Guid("5fecaddd-72c0-4bca-84d5-3ef56f7e93fb"),
                            CreatedAt = new DateTime(2022, 3, 25, 12, 59, 27, 751, DateTimeKind.Local).AddTicks(6134),
                            Email = "10",
                            IsAdmin = true,
                            LastName = "VSdsjFjKNV",
                            Name = "lnODcVSXaU",
                            Password = "10",
                            Phone = "10",
                            UpdateBy = new Guid("13b8dcf0-8afa-4aea-bd48-2d7ddfd3b089")
                        });
                });

            modelBuilder.Entity("Entities.Defect", b =>
                {
                    b.HasOne("Entities.Inventory", "Inventory")
                        .WithMany("DefectList")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Entities.Inventory", b =>
                {
                    b.HasOne("Entities.Department", null)
                        .WithMany("InventoryList")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Entities.Room", "Room")
                        .WithMany("InventoryList")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Setup", "Setup")
                        .WithMany("InventoryList")
                        .HasForeignKey("SetupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.User", "User")
                        .WithMany("InventoryList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");

                    b.Navigation("Setup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Room", b =>
                {
                    b.HasOne("Entities.Department", null)
                        .WithMany("RoomsList")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("Entities.Setup", b =>
                {
                    b.HasOne("Entities.Room", "Room")
                        .WithMany("SetupList")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.HasOne("Entities.Setup", "Setup")
                        .WithOne("User")
                        .HasForeignKey("Entities.User", "SetupId");

                    b.Navigation("Setup");
                });

            modelBuilder.Entity("Entities.Department", b =>
                {
                    b.Navigation("InventoryList");

                    b.Navigation("RoomsList");
                });

            modelBuilder.Entity("Entities.Inventory", b =>
                {
                    b.Navigation("DefectList");
                });

            modelBuilder.Entity("Entities.Room", b =>
                {
                    b.Navigation("InventoryList");

                    b.Navigation("SetupList");
                });

            modelBuilder.Entity("Entities.Setup", b =>
                {
                    b.Navigation("InventoryList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("InventoryList");
                });
#pragma warning restore 612, 618
        }
    }
}
